config/urls.py
from django.contrib import admin
from django.urls import include, path

from config import local_settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("home", include("home.urls")),
]

if local_settings.SQL_DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"

urlpatterns = [
    path("create", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/edit", views.TweetEditView.as_view(), name="edit"),
    path("<int:pk>/delete", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike", views.UnLikeView.as_view(), name="unlike"),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.views.generic import ListView

from tweets.models import Like, Tweet

User = get_user_model()


class HomeView(LoginRequiredMixin, ListView):
    """
    GET クエリ数:7
    """

    template_name = "home/home.html"
    model = Tweet
    context_object_name = "tweets"
    paginate_by = 6
    queryset = Tweet.objects.select_related("user").prefetch_related("likes")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        login_user = self.request.user
        context["user"] = User.objects.annotate(
            tweet_num=Count("tweets", distinct=True),
            following_num=Count("followers", distinct=True),
            follower_num=Count("following_users", distinct=True),
        ).get(username=login_user.username)
        context["liked_list"] = Like.objects.filter(user=login_user).values_list(
            "tweet", flat=True
        )
        return context

templates/home/home.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container">
  <div class="row">

    <div class="col-4">
      <div class="card">
        {% include 'components/user.html' %}
        <a class="btn btn-primary" href="{% url 'tweets:create' %}" role="button">Tweet</a>
      </div>
    </div>

    <div class="col-8">
      {% if messages %}
        {% for message in messages %}
          <div {% if message.tags %} class="{{ message.tags }} alert-dismissible in fade show" role="alert"{% endif %}>
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}

      {% include 'components/tweet.html' %}

      <div class="mt-3">
        {% bootstrap_pagination page_obj extra=request.GET.urlencode %}
      </div>
    </div>
  </div>
</div>
{% endblock %}