accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup", views.SignupView.as_view(), name="signup"),
    path(
        "login",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
    path("<slug:slug>", views.ProfileView.as_view(), name="profile"),
    path(
        "<slug:slug>/edit",
        views.ProfileEditView.as_view(),
        name="profile_edit",
    ),
    path("<slug:slug>/follow", views.FollowView.as_view(), name="follow"),
    path("<slug:slug>/unfollow", views.UnFollowView.as_view(), name="unfollow"),
    path(
        "<slug:slug>/following_list",
        views.FollowingListView.as_view(),
        name="following_list",
    ),
    path(
        "<slug:slug>/follower_list",
        views.FollowerListView.as_view(),
        name="follower_list",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

from config import local_settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("home", include("home.urls")),
]

if local_settings.SQL_DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

accounts/models.py
from django.conf import settings
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)
from django.contrib.auth.validators import ASCIIUsernameValidator
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify


class UserManager(BaseUserManager):
    def _create_user(self, email, username, password, **extra_fields):
        if not email:
            raise ValueError("The given email must be set")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            **extra_fields,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, username, password, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, username, password, **extra_fields)

    def create_superuser(self, email, username, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, username, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        error_messages={"unique": "このユーザー名はすでに使われています."},
        help_text="この項目は必須です. 150文字以下. 英数字, @/./+/-/_ だけが使えます.",
        unique=True,
        max_length=150,
        validators=[ASCIIUsernameValidator()],
        verbose_name="ユーザー名",
    )
    email = models.EmailField(
        error_messages={"unique": "このメールはすでに使われています."},
        help_text="この項目は必須です. 例:xxx@mail.com",
        unique=True,
        max_length=254,
        verbose_name="メール",
    )
    slug = models.SlugField(
        default="",
        unique=True,
        verbose_name="スラグ",
    )
    is_staff = models.BooleanField(
        verbose_name="管理者権限",
        default=False,
    )
    is_active = models.BooleanField(
        verbose_name="アクティブ",
        default=True,
    )

    objects = UserManager()

    # https://docs.djangoproject.com/en/4.1/topics/auth/customizing/#django.contrib.auth.models.CustomUser
    USERNAME_FIELD = "email"

    class Meta:
        db_table = "users"
        verbose_name = "ユーザー"
        verbose_name_plural = "ユーザー"

    def __str__(self):
        return self.email

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.username)
        return super().save(*args, **kwargs)


class FriendShip(models.Model):
    following = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="following_users",
        verbose_name="フォロー中",
    )
    follower = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="followers",
        verbose_name="フォロワー",
    )

    class Meta:
        db_table = "friendship"
        verbose_name = "フォロー中・フォロワー"
        verbose_name_plural = "フォロー中・フォロワー"
        constraints = [
            models.UniqueConstraint(
                fields=["following", "follower"], name="unique_friendship"
            ),
        ]

    def __str__(self):
        return f"{self.following.username} : {self.follower.username}"


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="ユーザー",
    )
    bio = models.TextField(
        blank=True,
        max_length=140,
        verbose_name="自己紹介",
    )

    class Meta:
        db_table = "profile"
        verbose_name = "プロフィール"
        verbose_name_plural = "プロフィール"

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def post_user_created(sender, instance, created, **kwargs):
    if created:
        profile_obj = Profile(user=instance)
        profile_obj.save()

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .models import Profile

User = get_user_model()


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "username")


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("bio",)
        widgets = {
            "bio": forms.Textarea(
                attrs={"rows": 5, "cols": 30, "placeholder": "ここに入力してください"}
            ),
        }

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, ListView, UpdateView, DetailView

from tweets.models import Tweet, Like

from .forms import ProfileEditForm, SignUpForm
from .models import FriendShip

User = get_user_model()


class SignupView(CreateView):
    """
    GET クエリ数:0
    POST クエリ数: 11 session状況によって12
    """

    form_class = SignUpForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("home:home")

    def form_valid(self, form):
        response = super().form_valid(form)
        email = form.cleaned_data["email"]
        password = form.cleaned_data["password1"]
        # authenticateでEmailAuthenticationBackendを呼び出している
        # EmailAuthenticationBackendを用いなくても、
        # USERNAME_FIELDにemailを設定していれば実際のところ必要ないが
        # あえて記述し、email=emailと書けるようにしている
        user = authenticate(self.request, email=email, password=password)
        login(self.request, user)
        return response


class ProfileView(LoginRequiredMixin, ListView):
    """
    GET クエリ数:8 (ログインユーザーの場合7)
    """

    template_name = "accounts/profile.html"
    model = Tweet
    context_object_name = "tweets"
    paginate_by = 6
    queryset = Tweet.objects.select_related("user").prefetch_related("likes")

    def get_queryset(self):
        u_qs = (
            User.objects.filter(slug=self.kwargs["slug"])
            .select_related("profile")
            .annotate(
                tweet_num=Count("tweets", distinct=True),
                following_num=Count("followers", distinct=True),
                follower_num=Count("following_users", distinct=True),
            )
        )
        self.target_user = get_object_or_404(u_qs, slug=self.kwargs["slug"])
        return self.queryset.filter(user=self.target_user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.target_user
        context["liked_list"] = Like.objects.filter(user=self.request.user).values_list(
            "tweet", flat=True
        )
        if self.request.user != self.target_user:
            context["is_following"] = FriendShip.objects.filter(
                following=self.target_user, follower=self.request.user
            ).exists()
        return context


class ProfileEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    GET クエリ数:3
    POST クエリ数:4
    """

    queryset = User.objects.select_related("profile")
    form_class = ProfileEditForm
    template_name = "accounts/profile_edit.html"

    def get_object(self):
        target_user = get_object_or_404(self.queryset, slug=self.kwargs["slug"])
        return target_user.profile

    def get_success_url(self):
        return reverse("accounts:profile", kwargs={"slug": self.request.user.slug})

    def test_func(self):
        return self.request.user.slug == self.kwargs["slug"]


class FollowView(LoginRequiredMixin, View):
    """
    POST クエリ数:5
    """

    def post(self, request, *args, **kwargs):
        follower = self.request.user
        # self.kwargs["slug"]だとTypeError
        # got an unexpected keyword argument 'slug'
        following = get_object_or_404(User, slug=kwargs["slug"])
        if follower == following:
            messages.warning(self.request, "自分をフォローすることはできません")
        elif FriendShip.objects.filter(follower=follower, following=following).exists():
            messages.warning(self.request, f"あなたはすでに{ following.username }をフォローしています")
        else:
            FriendShip(follower=follower, following=following).save()
        return redirect("home:home")


class UnFollowView(LoginRequiredMixin, View):
    """
    POST クエリ数:6
    """

    def post(self, request, *args, **kwargs):
        follower = self.request.user
        following = get_object_or_404(User, slug=kwargs["slug"])
        if FriendShip.objects.filter(follower=follower, following=following).exists():
            FriendShip.objects.filter(follower=follower, following=following).delete()
        else:
            messages.warning(self.request, "無効な操作です")
        return redirect("home:home")


class FollowingListView(LoginRequiredMixin, DetailView):
    """
    GET クエリ数:5 (2 similar)
    """

    model = User
    template_name = "accounts/following_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        following_users = FriendShip.objects.filter(follower=self.object).values_list(
            "following"
        )
        context["following_list"] = User.objects.filter(id__in=following_users)
        following_users_by_login_user = (
            FriendShip.objects.select_related("follower")
            .filter(follower=self.request.user)
            .values_list("following")
        )
        context["following_by_login_user"] = User.objects.filter(
            id__in=following_users_by_login_user
        )
        return context


class FollowerListView(LoginRequiredMixin, DetailView):
    """
    GET クエリ数:5
    """

    model = User
    template_name = "accounts/follower_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        followers = FriendShip.objects.filter(following=self.object).values_list(
            "follower"
        )
        context["follower_list"] = User.objects.filter(id__in=followers)
        following_users_by_login_user = FriendShip.objects.filter(
            follower=self.request.user
        ).values_list("following")
        context["following_by_login_user"] = User.objects.filter(
            id__in=following_users_by_login_user
        )
        return context

templates/accounts/follower_list.html
{% extends "base.html" %}

{% block title %}Follower List{% endblock %}

{% block content %}
<div class="content-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6 offset-sm-3">
        <div class="table table-responsive">
          <table id='follower_list' class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th class="text-center" style="width: 50%">ユーザー</th>
                <th class="text-center" style="width: 50%">フォロー/アンフォロー</th>
              </tr>
            </thead>
            <tbody>
              {% for follower in follower_list %}
                <tr class="text">
                  <td class="text-center">{{ follower.username }}</td>
                  <td class="text-center align-middle">
                  {% if follower != request.user %}
                    {% if follower in following_by_login_user %}
                      <form action="{% url 'accounts:unfollow' follower.slug %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-danger btn-sm" name="button">
                          アンフォロー
                        </button>
                      </form>
                    {% else %}
                      <form action="{% url 'accounts:follow' follower.slug %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-primary btn-sm" name="button">
                          フォロー
                        </button>
                      </form>
                    {% endif %}
                  {% endif %}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/accounts/following_list.html
{% extends "base.html" %}

{% block title %}Following List{% endblock %}

{% block content %}
<div class="content-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6 offset-sm-3">
        <div class="table table-responsive">
          <table id='following_list' class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th class="text-center" style="width: 50%">ユーザー</th>
                <th class="text-center" style="width: 50%">フォロー/アンフォロー</th>
              </tr>
            </thead>
            <tbody>
              {% for following in following_list %}
                <tr class="text">
                  <td class="text-center">{{ following.username }}</td>
                  <td class="text-center align-middle">
                  {% if following != request.user %}
                    {% if following in following_by_login_user %}
                      <form action="{% url 'accounts:unfollow' following.slug %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-danger btn-sm" name="button">
                          アンフォロー
                        </button>
                      </form>
                    {% else %}
                      <form action="{% url 'accounts:follow' following.slug %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-primary btn-sm" name="button">
                          フォロー
                        </button>
                      </form>
                    {% endif %}
                  {% endif %}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load widget_tweaks %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-lg-4 col-md-6 col-sm-8">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">ログイン</h3>
        <form method="post" novalidate>
          {% csrf_token %}
          <ul class="list-unstyled text-danger">
            {% for error in form.non_field_errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% for field in form %}
            <div class="mb-3">
              <label for="{{ field.id_for_label }}" class="form-label">
              {{ field.label }}
              </label>
              {% if field.errors or form.non_field_errors %}
                {% render_field field class="form-control is-invalid" placeholder=field.label %}
                {% for error in field.errors %}
                  <div class="invalid-feedback">{{ error }}</div>
                {% endfor %}
              {% else %}
                {% render_field field class="form-control" placeholder=field.label %}
              {% endif %}
            </div>
          {% endfor %}
          <button type="submit" class="btn btn-outline-primary btn-block">ログイン</button>
        </form>
      </div>
      <div class="card-footer text-muted text-center">
          初めての方はこちら： <a href="{% url 'accounts:signup' %}">アカウント登録</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/accounts/profile.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}Profile{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">

    <div class="col-4">
      <div class="card text-center">
        {% include 'components/user.html' %}
        {% if request.user == user %}
          <a class="btn btn-primary" href="{% url 'accounts:profile_edit' user.slug %}" role="button">プロフィール編集</a>
        {% else %}
          {% if is_following %}
            <form action="{% url 'accounts:unfollow' user.slug %}" method="post">
              {% csrf_token %}
              <div class="d-grid gap-2">
                <button type="submit" class="btn btn-outline-danger btn-lg" name="button">
                  アンフォロー
                </button>
              </div>
            </form>
          {% else %}
          <form action="{% url 'accounts:follow' user.slug %}" method="post">
            {% csrf_token %}
            <div class="d-grid gap-2">
              <button type="submit" class="btn btn-outline-primary" name="button">
                フォロー
              </button>
            </div>
            </form>
          {% endif %}
        {% endif %}
      </div>
    </div>

    <div class="col-8">

      <div class="card text-white bg-primary mb-3">
        <div class="card-body">
          <p class="card-title">自己紹介</p>
          <p class="mb-3 card-text">{{ user.profile.bio }}</p>
        </div>
      </div>

      {% include 'components/tweet.html' %}

      <div class="mt-3">
        {% bootstrap_pagination page_obj extra=request.GET.urlencode %}
      </div>
    </div>

  </div>
</div>
{% endblock %}

templates/accounts/profile_edit.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}Profile Edit{% endblock %}

{% block content %}
<div class="content-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6 offset-sm-3">
        <div class="card">
          <div class="card-header">
            <h4><b>プロフィール編集</b></h4>
          </div>
          <div class="card-body">
            <form method="post">
              {% csrf_token %}
              {% bootstrap_form form %}
              <button type="submit" class="btn btn-outline-primary btn-block">
                更新
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/accounts/signup.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-lg-8 col-md-10 col-sm-12">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title mb-3">サインアップ</h3>
        <form method="post" novalidate>
          {% csrf_token %}
          {% bootstrap_form form %}
          <button type="submit" class="btn btn-outline-primary btn-block">アカウント作成</button>
        </form>
      </div>
      <div class="card-footer text-muted text-center">
        すでにアカウントを持っている方はこちら： <a href="{% url 'accounts:login' %}">ログイン</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}