accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup", views.SignupView.as_view(), name="signup"),
    path(
        "login",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
    path("<slug:slug>", views.ProfileView.as_view(), name="profile"),
    path(
        "<slug:slug>/edit",
        views.ProfileEditView.as_view(),
        name="profile_edit",
    ),
    path("<slug:slug>/follow", views.FollowView.as_view(), name="follow"),
    path("<slug:slug>/unfollow", views.UnFollowView.as_view(), name="unfollow"),
    path(
        "<slug:slug>/following_list",
        views.FollowingListView.as_view(),
        name="following_list",
    ),
    path(
        "<slug:slug>/follower_list",
        views.FollowerListView.as_view(),
        name="follower_list",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

from config import local_settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("home", include("home.urls")),
]

if local_settings.SQL_DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load django_bootstrap5 %}
{% load widget_tweaks %}
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Twitter Clone{% endblock %}</title>

    <!-- Bootstrap5 CSS JS -->
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <!-- tailwindcss -->
    <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body>
    <!-- header  -->
    <header class="mb-3">
      <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
        <div class="container-md">
          <a class="navbar-brand" href="{% url 'home:home' %}">Twitter Clone</a>
          {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'home:home' %}">Home</a>
            <a class="navbar-brand" href="{% url 'accounts:logout' %}">Logout</a>
          {% else %}
            <a class="navbar-brand" href="{% url 'accounts:login' %}">Login</a>
            <a class="navbar-brand" href="{% url 'accounts:signup' %}">Sign up</a>
          {% endif %}
        </div>
      </nav>
    </header>
    <!-- /header  -->

    <!-- main  -->
    <main>
    {% block content %}
    {% endblock %}
    </main>
    <!-- /main  -->

    <script src="{% static 'ajax.js' %}"></script>
  </body>
</html>