accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup", views.SignupView.as_view(), name="signup"),
    path(
        "login",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
    path("<slug:slug>", views.ProfileView.as_view(), name="profile"),
    path(
        "<slug:slug>/edit",
        views.ProfileEditView.as_view(),
        name="profile_edit",
    ),
    path("<slug:slug>/follow", views.FollowView.as_view(), name="follow"),
    path("<slug:slug>/unfollow", views.UnFollowView.as_view(), name="unfollow"),
    path(
        "<slug:slug>/following_list",
        views.FollowingListView.as_view(),
        name="following_list",
    ),
    path(
        "<slug:slug>/follower_list",
        views.FollowerListView.as_view(),
        name="follower_list",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

from config import local_settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("home", include("home.urls")),
]

if local_settings.SQL_DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"

urlpatterns = [
    path("create", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/edit", views.TweetEditView.as_view(), name="edit"),
    path("<int:pk>/delete", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike", views.UnLikeView.as_view(), name="unlike"),
]

tweets/models.py
from django.conf import settings
from django.db import models


class Tweet(models.Model):
    content = models.CharField(
        max_length=140,
        verbose_name="ツイート",
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="ユーザー",
        related_name="tweets",
    )
    created_at = models.DateTimeField(
        verbose_name="作成日時",
        auto_now_add=True,
    )

    class Meta:
        db_table = "tweets"
        ordering = ["-created_at"]
        verbose_name = "ツイート"
        verbose_name_plural = "ツイート"

    def __str__(self):
        return f"{self.user.username} : {self.content}"


class Like(models.Model):
    tweet = models.ForeignKey(
        Tweet,
        on_delete=models.CASCADE,
        verbose_name="ツイート",
        related_name="likes",
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="ユーザー",
        related_name="likes",
    )

    class Meta:
        db_table = "like"
        verbose_name = "いいね"
        verbose_name_plural = "いいね"
        constraints = [
            models.UniqueConstraint(fields=["tweet", "user"], name="unique_like"),
        ]

    def __str__(self):
        return f"{self.user.username} : {self.tweet.content}"

tweets/forms.py
from django import forms

from .models import Tweet


class TweetBaseForm(forms.ModelForm):
    class Meta:
        model = Tweet
        fields = ("content",)
        widgets = {
            "content": forms.Textarea(
                attrs={"rows": 5, "cols": 30, "placeholder": "ここに入力してください"}
            ),
        }


class TweetCreateForm(TweetBaseForm):
    pass


class TweetEditForm(TweetBaseForm):
    class Meta(TweetBaseForm.Meta):
        widgets = {
            "content": forms.Textarea(attrs={"rows": 5, "cols": 30}),
        }

tweets/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, DeleteView, UpdateView

from .forms import TweetCreateForm, TweetEditForm
from .models import Like, Tweet

User = get_user_model()


class TweetCreateView(LoginRequiredMixin, CreateView):
    """
    GET クエリ数:2
    POST クエリ数:3
    """

    form_class = TweetCreateForm
    template_name = "tweets/create.html"
    success_url = reverse_lazy("home:home")

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, "ツイートが完了しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, "ツイートが失敗しました")
        return super().form_invalid(form)


class TweetEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    GET クエリ数:3
    POST クエリ数:4
    """

    queryset = Tweet.objects.select_related("user")
    form_class = TweetEditForm
    template_name = "tweets/edit.html"
    success_url = reverse_lazy("home:home")

    def get(self, request, *args, **kwargs):  # self.get_object()を呼び出すのを防ぐためにオーバーライド
        return self.render_to_response(self.get_context_data())

    def post(self, request, *args, **kwargs):  # self.get_object()を呼び出すのを防ぐためにオーバーライド
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        messages.success(self.request, "更新が完了しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, "更新が失敗しました")
        return super().form_invalid(form)

    def test_func(self):
        self.object = self.get_object()
        return self.request.user == self.object.user


class TweetDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    GET クエリ数:3
    POST クエリ数:6
    """

    queryset = Tweet.objects.select_related("user")
    template_name = "tweets/delete.html"
    success_url = reverse_lazy("home:home")
    success_message = "ツイートは削除されました"

    def get(self, request, *args, **kwargs):  # self.get_object()を呼び出すのを防ぐためにオーバーライド
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):  # self.get_object()を呼び出すのを防ぐためにオーバーライド
        return self.delete(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):  # self.get_object()を呼び出すのを防ぐためにオーバーライド
        messages.success(self.request, self.success_message)
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)

    def test_func(self):
        self.object = self.get_object()
        return self.request.user == self.object.user


class LikeView(LoginRequiredMixin, View):
    """
    POST クエリ数:7
    """

    def post(self, request, *args, **kwargs):
        tweet = get_object_or_404(Tweet, pk=kwargs["pk"])
        Like.objects.get_or_create(user=self.request.user, tweet=tweet)
        likes_count = tweet.likes.count()
        context = {
            "tweet_id": tweet.id,
            "likes_count": likes_count,
            "is_liked": True,
        }
        return JsonResponse(context)


class UnLikeView(LoginRequiredMixin, View):
    """
    POST クエリ数:7
    """

    def post(self, request, *args, **kwargs):
        tweet = get_object_or_404(Tweet, pk=kwargs["pk"])
        if like := Like.objects.filter(user=self.request.user, tweet=tweet):
            like.delete()
        likes_count = tweet.likes.count()
        context = {
            "tweet_id": tweet.id,
            "likes_count": likes_count,
            "is_liked": False,
        }
        return JsonResponse(context)

templates/components/like.html
<div class="d-flex align-items-center space-x-1">
  {% if tweet.id in liked_list %}
    <button data-button="like" data-url="{% url 'tweets:unlike' tweet.pk %}">
      <svg xmlns="http://www.w3.org/2000/svg" id="heart" class="h-4 w-4 cursor-pointer text-pink-500" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clip-rule="evenodd" />
      </svg>
    </button>
  {% else %}
    <button data-button="like" data-url="{% url 'tweets:like' tweet.pk %}">
      <svg xmlns="http://www.w3.org/2000/svg" id="blank-heart" class="h-4 w-4 cursor-pointer hover:text-pink-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
        <path stroke-linecap="round" stroke-linejoin="round" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
      </svg>
    </button>
  {% endif %}
  <span name="count_{{tweet.id}}" class="count">{{ tweet.likes.count }}</span>
</div>

templates/components/tweet.html
{% for tweet in tweets %}
<div class="card">
  <div class="card-body">
    <a href="{% url 'accounts:profile' tweet.user.slug %}">{{ tweet.user.username }}</a> | {{ tweet.created_at }}
    <p class="mb-3 card-text">{{ tweet.content | linebreaksbr }}</p>

    <div class="flex justify-content-start space-x-6">
      {% include 'components/like.html' %}
      {% if tweet.user == request.user %}
        <a href="{% url 'tweets:edit' tweet.pk %}" role="button">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 cursor-pointer hover:text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
            </svg>
        </a>
        <a href="{% url 'tweets:delete' tweet.pk %}" role="button">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 cursor-pointer hover:text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
            </svg>
        </a>
      {% endif %}
    </div>
  </div>
</div>
{% endfor %}

templates/components/user.html
<div class="card-header">
  <h2 class="fs-2 fw-bolder text-center"><a href="{% url 'accounts:profile' user.slug %}">{{ user.username }}</a></h2>
</div>
<div class="card-body text-center">
  <ul class="nav nav-tabs flex-column nav-start mb-3">
    <li class="nav-item mb-3">
      ツイート数<span>{{ user.tweet_num }}</span>
    </li>
    <li class="nav-item">
      <a href="{% url 'accounts:following_list' user.slug %}" class="nav-link">
        フォロー数<span>{{ user.following_num }}</span>
      </a>
    </li>
    <li class="nav-item">
      <a href="{% url 'accounts:follower_list' user.slug %}" class="nav-link">
        フォロワー数<span>{{ user.follower_num }}</span>
      </a>
    </li>
  </ul>
</div>